### ISSUE TITLE
imread crashes when loading large png 16-bit files larger than int size

### ISSUE THREAD

**Issue by jplanner** [Itseez/opencv#6317]
OpenCV crashes when loading large 16-bit png images (> 2.4 GB uncompressed). There is probably bug in file grfmt_png.cpp on line 284:

for( y = 0; y < m_height; y++ )
    buffer[y] = data + y*step;

where step variable is int (y * step overflows). Easy fix should probably be not to cast step from size_t to int but use img.step directly:

for( y = 0; y < m_height; y++ )
    buffer[y] = data + y*img.step;

### Please state the information for your system
- OpenCV version: 3.1
- Host OS: Windows 10

### In which part of the OpenCV library you got the issue?
imagecodecs
### Expected behaviour
Application should not crash

### Actual behaviour
Application crashes

### Code example to reproduce the issue / Steps to reproduce the issue
auto img = imread("large_16_bit_png.png", -1);

**Comment by kevin-coder** [comment]
hi, I am willing to investigate this bug, @jplanner , could you please share me the large png file or share me the way to generate such kind of large png file? So that I can re-produce this bug.

**Comment by jplanner** [comment]
Hello, thank you for investigating this bug. Below is link for desired file. (Link is valid for 7 days from now). http://support.tescan.com/tmpfiles/download.php?file=32kx-32kx-2-16bpp.png

**Comment by RSaracchini** [comment]
I can confirm this bug on Linux (Debian "Wheezy" 64-Bit) with OpenCV (either 2.4 or 3.1). The application crashes  when I load 16-bit  PGM images using the flag "CV_LOAD_IMAGE_GRAYSCALE". "cv::imread" does not fail or give apparent problems. However, trying to clone the cv::Mat object or going out of the scope where the variable is declared causes a crash.  The crash doesn't happen when it is loaded without this flag. 

I have attached the image for debug purposes.  The backtrace shows that the crash happened in libopencv_core.so.3.1. 

[Scene_Persp0001.zip](https://github.com/Itseez/opencv/files/227709/Scene_Persp0001.zip)

**Comment by Dikay900** [comment]
can you test the latest master of the 2.4 since the PR which should resolve this was merged?

**Comment by RSaracchini** [comment]
Sure. I' ll compile it in my dev. environment and see if the issue persists.

**Comment by Dikay900** [comment]
please report back if this is fixed so this can be closed. Thank you!

**Comment by RSaracchini** [comment]
The error persists with the master version of OpenCV 2.4.
The test case which causes the crash is the following:

`cv::Mat test_image =cv::imread("Scene_Persp0001.pgm",CV_LOAD_IMAGE_GRAYSCALE);`
`cv::Mat image_copy = test_image.clone();`

**Comment by kevin-coder** [comment]
I will take a look at this issue ASAP

**Comment by kevin-coder** [comment]
@Dikay900 , the root cause for issue reported by @RSaracchini is not the same with previous fix. 
The root cause for this issue is: when calling imread to read the pgm file, when returning with success reading file, the destructor will free the resource which used by memcpy, but in the code, the resource calculation was not correct, therefore, it will cause memory corruption during resource free.
I suggest to file a another bug for this issue because I believe the root cause is not the same with bug 6317. If so, could @RSaracchini file another new bug? Thanks!
I will create a PR for this issue once the new bug would be filed.

**Comment by kevin-coder** [comment]
#6445 has been filed for issue reported by @RSaracchini .

**Comment by Dikay900** [comment]
ah i misread pgm. thanks for filing a new issue
@alalek this can be closed now unsure why the buildbot did not close this

**Comment by alalek** [comment]
@Dikay900 This waits for master fix. Merge 2.4 process is in progress
