### ISSUE TITLE
std::tuple errors when Building OpenCV for Microsoft VS 2015 (x64)

### ISSUE THREAD

**Issue by oracle3001** [Itseez/opencv#6716]
- OpenCV version: 3.x main branch
- Host OS: Windows 10
- Compiler & CMake: Visual Studio 2015 (update 1), Cuda 8RC & CMake 3.5

A large number of compiler errors related to std::tuple in lots of opencv_perf_cudaxxx... e.g opencv_perf_cudaimproc, opencv_perf_cudaarithm, opencv_perf_cudastereo, opencv_perf_cudalegacy, 

```
Severity	Code	Description	File	Project	Line	Suppression State
Error	C2610	'std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth>::tuple(const std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth> &)': is not a special member function which can be defaulted (compiling source file D:\Data\My Documents\GitHub\opencv\modules\cudaarithm\perf\perf_element_operations.cpp)	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\tuple	opencv_perf_cudaarithm	328	



```

```
Severity	Code	Description	File	Project	Line	Suppression State
Error	C2535	'std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth,perf::`anonymous-namespace'::MatCn> &std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth,perf::`anonymous-namespace'::MatCn>::operator =(const std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth,perf::`anonymous-namespace'::MatCn> &)': member function already defined or declared (compiling source file D:\Data\My Documents\GitHub\opencv\modules\cudawarping\perf\perf_warping.cpp)	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\tuple	opencv_perf_cudawarping	463	

```

**Comment by pansk** [comment]
Hi, same problem here.
I also found there at least a third type of error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2382	'std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth>::operator =': redefinition; different exception specifications (compiling source file D:\libs\opencv-3.1.0\sources\modules\cudaarithm\perf\perf_element_operations.cpp)	opencv_perf_cudaarithm	D:\libs\opencv-3.1.0\sources\modules\ts\include\opencv2\ts\cuda_perf.hpp	75

**Comment by timmxc** [comment]
same problem too, with CUDA & vs2015 x64
remove cuda will be OK

**Comment by sammoes** [comment]
This seems similar to #5007 but not the same, the files involved are different. cf. @thebucc 's comment:
I need OpenCL active (I think, not sure every OpenCL implementation has a CUDA variant) but will try without OpenCL. C2382 (cuda_perf.hpp), C2610 and C2535 (C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\tuple) are the error codes I am getting, with complex messages.

I think we have to reopen this: the original problem is still present. The issue described by @patrikhuber is different, and is in fact fixed by change #4122 (by the way only the change in core/mat.inl.hpp on line 1603 is necessary).
This problem appears only with openCL enabled: I can only assume that @patrikhuber doesn't have WITH_OPENCL set in cmake so the bug isn't triggered. The solution is easy, although I'm not 100% sure of why it works.

The problem is the definition of Size_MatDepth_t and Size_MatDepth: they are currently in modules\ts\include\opencv2\ts\ts_perf.hpp (lines 480-481) but are only used in modules\core\perf\opencl\perf_channels.cpp. Moving those two typedefs from ts_perf.hpp to perf_channels.cpp (e.g. on line 159) fixes the build error and it is possible to run all the tests.
As I said, I'm not so sure about why it works: I guess there is a clash of namespaces, but I haven't really investigated.

**Comment by RichInSoquel** [comment]
Still get these errors with OpenCV even without WITH_OPENCL

4>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\tuple(717): note: see declaration of 'std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth,perf::`anonymous-namespace'::MatCn>::operator ='
3>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\tuple(607): error C2610: 'std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth>::tuple(const std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth> &)': is not a special member function which can be defaulted
3>  C:\indec\source\OpenSource\Snakes15\openCV\modules\cudastereo\perf\perf_stereo.cpp(199): note: see reference to class template instantiation 'std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth>' being compiled
3>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\tuple(608): error C2610: 'std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth>::tuple(std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth> &&)': is not a special member function which can be defaulted
3>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\tuple(756): error C2535: 'std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth> &std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth>::operator =(const std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth> &)': member function already defined or declared
3>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\tuple(650): note: see declaration of 'std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth>::operator ='
3>C:\indec\source\OpenSource\Snakes15\openCV\modules\ts\include\opencv2/ts/cuda_perf.hpp(72): error C2382: 'std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth>::operator =': redefinition; different exception specifications


Snippets from opencv_version output 

General configuration for OpenCV 3.3.0-dev =====================================
...
  Platform:
    Timestamp:                   2017-08-14T20:47:40Z
    Host:                        Windows 10.0.15063 AMD64
    CMake:                       3.9.0
    CMake generator:             Visual Studio 14 2015 Win64
    CMake build tool:            C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe
...
Other third-party libraries:
    Use Intel IPP:               2017.0.2 [2017.0.2]
               at:               C:/indec/source/OpenSource/Snakes15/openCV/build/3rdparty/ippicv/ippicv_win
    Use Intel IPP IW:            prebuilt binaries (2017.0.2)
    Use Intel IPP Async:         NO
    Use Lapack:                  NO
    Use Eigen:                   NO
    Use Cuda:                    YES (ver 8.0)
    Use OpenCL:                  NO
    Use OpenVX:                  NO
    Use custom HAL:              NO

Is this the same issue?

**Comment by alalek** [comment]
Yes, looks like it is CUDA issue. Could you try to update CUDA 8.0 version (or try CUDA 9.0 RC)?

**Comment by RichInSoquel** [comment]
Thanks for your suggestion.  I downloaded latest CUDA 8.0 and CUDA Patch 2, which say they are CUDA version 8.0.61, but after installing both and restarting, when I run 
     nvcc --version
it still reports "Cuda compilation tools, release 8.0, V8.0.60"

Rebuilding, still get identical errors... Hmmm...

**Comment by drcdr** [comment]
I'm seeing this as well.  I'm using OpenCV 3.3, VS2017 (15.3.0), CUDA 9.0 RC, CUDNN 7, CMAKE 3.9.1, and Windows10.  Other settings include Eigen 3.3.4, Maxwell, CUBLAS, OpenMP, TBB, MKL, CXX11.  I can send more settings details, if needed.

After some effort, I got everything to build, except for: opencv_perf_cudastereo.vcxproj, opencv_perf_cudaarithm.vcxproj, opencv_perf_cudawarping.vcxproj, opencv_perf_cudaimgproc.vcxproj

I get similar 'std::tuple' errors, as above.  But, one thing is slightly different - I get an **INTERNAL COMPILER ERROR** as well.  (I have not yet filed a ticket with MS.)  Here is a snippet:

3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\tuple(535): error C2610: 'std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth>::tuple(const std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth> &)': is not a special member function which can be defaulted (compiling source file C:\Cpp\3rdparty\opencv33\opencv\modules\cudaarithm\perf\perf_element_operations.cpp)
3>C:\Cpp\3rdparty\opencv33\opencv\modules\cudaarithm\perf\perf_element_operations.cpp(58): note: see reference to class template instantiation 'std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth>' being compiled
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\tuple(536): error C2610: 'std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth>::tuple(std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth> &&)': is not a special member function which can be defaulted (compiling source file C:\Cpp\3rdparty\opencv33\opencv\modules\cudaarithm\perf\perf_element_operations.cpp)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\tuple(674): error C2535: 'std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth> &std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth>::operator =(const std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth> &)': member function already defined or declared (compiling source file C:\Cpp\3rdparty\opencv33\opencv\modules\cudaarithm\perf\perf_element_operations.cpp)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\tuple(574): note: see declaration of 'std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth>::operator =' (compiling source file C:\Cpp\3rdparty\opencv33\opencv\modules\cudaarithm\perf\perf_element_operations.cpp)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\tuple(674): fatal error C1903: unable to recover from previous error(s); stopping compilation (compiling source file C:\Cpp\3rdparty\opencv33\opencv\modules\cudaarithm\perf\perf_element_operations.cpp)
**3>INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX86\x64\CL.exe'**
3>    Please choose the Technical Support command on the Visual C++
3>    Help menu, or open the Technical Support help file for more information

**Comment by RichInSoquel** [comment]
Should we be reporting this to Nvidia as well as Microsoft?

**Comment by drcdr** [comment]
In opencv_perf_cudaarithm, there are 3 files that give the INTERNAL COMPILER ERROR - 
- perf_core.cpp 
- perf_element_operations.cpp
- perf_reductions.cpp

By commenting out functions successively in perf_core.cpp to see which ones cause the compiler error, it can be seen that the (first two) Merge and Split functions are the cause of the problem. 

File perf_core.cpp can be made to compile by adding the following at the top of the file:
```
DEF_PARAM_TEST(Sz_Depth_Cn, cv::Size, MatDepth, MatCn);
```
Similarly, perf_element_operations.cpp and perf_reductions.cpp will compile if these are added at the top:
```
DEF_PARAM_TEST(Sz_Depth, cv::Size, MatDepth);
DEF_PARAM_TEST(Sz_Depth_Cn, cv::Size, MatDepth, MatCn);
```
opencv_perf_cudaarithm now builds, and runs:

```
[----------] Global test environment tear-down
[==========] 1839 tests from 66 test cases ran. (51631 ms total)
[  PASSED  ] 1839 tests.
```

**Comment by kevin-coder** [comment]
Tried with CUDA 9, still, have this issue.

11>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\tuple(607): error C2610: 'std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth>::tuple(const std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth> &)': is not a special member function which can be defaulted (compiling source file C:\1Work\1Research\1openSource\opencv-fork\modules\cudaarithm\perf\perf_element_operations.cpp)
13>  perf_stereo.cpp
11>  C:\1Work\1Research\1openSource\opencv-fork\modules\cudaarithm\perf\perf_element_operations.cpp(58): note: see reference to class template instantiation 'std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth>' being compiled
11>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\tuple(608): error C2610: 'std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth>::tuple(std::tuple<cv::Size,perf::`anonymous-namespace'::MatDepth> &&)': is not a special member function which can be defaulted (compiling source file C:\1Work\1Research\1openSource\opencv-fork\modules\cudaarithm\perf\perf_element_operations.cpp)

**Comment by cbyzju** [comment]
so any guy knows how to solve this problem?

**Comment by kevin-coder** [comment]
@cbyzju, solutions from johnhany in this thread is a walk-around if you don't mind to disable BUILD_PERF_TESTS and BUILD_TESTS in cmake configurations.

**Comment by huaweiping** [comment]
Using OpenCV 3.4.0+CUDA 8.0.61+Visual Studio 2015, the same problem is still appeared. And I'm tring for the solution from @drcdr now...
